version: 2

run:
  timeout: 5m
  tests: true

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
    - revive
    - gocritic

formatters:
  enable:
    - gofmt
    - goimports

linters-settings:
  errcheck:
    check-blank: true
  govet:
    check-shadowing: true
  revive:
    rules:
      - name: exported
        disabled: true

formatters-settings:
  gofmt:
    simplify: true

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
